// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdZNTQSr-tY552Vvrp0vQNXtXRZyFRYD0',
    appId: '1:500253204530:web:999e081b012701cdcd5c2b',
    messagingSenderId: '500253204530',
    projectId: 'flutter-riverpod-practice',
    authDomain: 'flutter-riverpod-practice.firebaseapp.com',
    storageBucket: 'flutter-riverpod-practice.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRN0p-0QZJ8n_W6vLrCSJjBv0jqFH2xO0',
    appId: '1:500253204530:android:c8ec8af89f23b10fcd5c2b',
    messagingSenderId: '500253204530',
    projectId: 'flutter-riverpod-practice',
    storageBucket: 'flutter-riverpod-practice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_xIdiYzpTfQkqO0n1Z-dwOyDmjF0qTUg',
    appId: '1:500253204530:ios:9a2e76101e47aedacd5c2b',
    messagingSenderId: '500253204530',
    projectId: 'flutter-riverpod-practice',
    storageBucket: 'flutter-riverpod-practice.appspot.com',
    iosBundleId: 'com.example.flutterRiverpodPractice1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_xIdiYzpTfQkqO0n1Z-dwOyDmjF0qTUg',
    appId: '1:500253204530:ios:7ad763f33c852dcacd5c2b',
    messagingSenderId: '500253204530',
    projectId: 'flutter-riverpod-practice',
    storageBucket: 'flutter-riverpod-practice.appspot.com',
    iosBundleId: 'com.example.flutterRiverpodPractice1.RunnerTests',
  );
}
